version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/web/staticfiles
      - media_volume:/app/web/mediafiles
    env_file:
      - .env
    networks:
        - backend
    depends_on:
      - db

  db:                                         # DB_HOST
    restart: always
    image: postgres
    container_name: db
    expose:                                   # DB_PORT
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgresdb                # DB_NAME
      - POSTGRES_PASSWORD=PASSWORD@123        # DB_PASSWORD
      # - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
        - backend


networks:
  backend:
    name: backend-network
    driver: bridge


volumes:
  postgres-data:
  static_volume:
  media_volume: