version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
